// src/lib/svelte/settings/Settings.svelte
<script lang="ts">
    import { onMount } from 'svelte'
    import type { Settings } from '../../types.js'

    let loading    = $state(true)
    let error      = $state<string | null>(null)
    let settings   = $state<Partial<Settings>>({})
    let flagCounts = $state({ childLocked: 0, filtered: 0 })

    let showBlocklist = $state(false)
    let newTerm       = $state('')

    onMount(async () => {
        try {
            const [settingsRes, flagsRes] = await Promise.all([
                fetch('/api/settings'),
                fetch('/api/flags').catch(() => null),
            ])
            if (!settingsRes.ok) throw new Error(`HTTP ${settingsRes.status}`)
            settings = await settingsRes.json()

            const flags   = flagsRes?.ok ? await flagsRes.json() : {}
            const entries: { childLock?: boolean; filtered?: boolean }[] = Object.values(flags)
            flagCounts = {
                childLocked: entries.filter(f => f?.childLock).length,
                filtered:    entries.filter(f => f?.filtered).length,
            }
        } catch (err) {
            error = (err as Error).message
        }
        loading = false
    })

    // Every content-filter toggle in the UI means the same thing: ON = hide, OFF = show.
    // Some underlying settings are stored the opposite way ("show X" = true means visible),
    // so those rows pass invert=true — the UI checkbox is the negation of the stored value.
    async function onToggle(key: keyof Settings, checked: boolean, invert = false) {
        const prev = settings[key]
        settings[key] = invert ? !checked : checked
        try {
            const res = await fetch('/api/settings', {
                method:  'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body:    JSON.stringify({ [key]: settings[key] }),
            })
            if (!res.ok) throw new Error(`HTTP ${res.status}`)
        } catch {
            settings[key] = prev
        }
    }

    async function saveBlocklist(list: string[]) {
        const prev = settings.titleBlocklist
        settings.titleBlocklist = list
        try {
            const res = await fetch('/api/settings', {
                method:  'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body:    JSON.stringify({ titleBlocklist: list }),
            })
            if (!res.ok) throw new Error(`HTTP ${res.status}`)
            try { localStorage.setItem('disc-title-blocklist', JSON.stringify(list)) } catch {}
        } catch {
            settings.titleBlocklist = prev
        }
    }

    async function addTerm() {
        const term = newTerm.trim().toLowerCase()
        if (!term) return
        await saveBlocklist([...(settings.titleBlocklist ?? []), term])
        newTerm = ''
    }

    async function removeTerm(i: number) {
        await saveBlocklist((settings.titleBlocklist ?? []).filter((_, idx) => idx !== i))
    }
</script>

{#if loading}
    <p class="page-loading">Loading settings…</p>
{:else if error}
    <p class="page-error">Failed to load settings: {error}</p>
{:else}
    <div class="page-header">
        <h1 class="page-title">Settings</h1>
    </div>
    <div class="settings-body">
        <section class="settings-section">
            <h2 class="settings-section-title">Content Filters</h2>
            <p class="settings-section-desc">
                Every toggle here works the same way: <strong>on hides, off shows</strong>.
                Games flagged as Child Lock or Filtered are hidden by default — turn a toggle off to reveal them.
            </p>

            <label class="settings-toggle-row">
                <div class="settings-toggle-text">
                    <span class="settings-toggle-label">
                        Hide Child Locked Games
                        {#if flagCounts.childLocked > 0}
                            <span class="settings-filter-count">{flagCounts.childLocked} game{flagCounts.childLocked === 1 ? '' : 's'}</span>
                        {/if}
                    </span>
                    <span class="settings-toggle-desc">Hide games flagged with the child lock from library, wishlist, and all other lists.</span>
                </div>
                <div class="settings-toggle-switch">
                    <input type="checkbox" checked={!settings.showChildLocked}
                           onchange={(e) => onToggle('showChildLocked', e.currentTarget.checked, true)}>
                    <span class="settings-toggle-track"></span>
                </div>
            </label>

            <label class="settings-toggle-row">
                <div class="settings-toggle-text">
                    <span class="settings-toggle-label">
                        Hide Filtered Games
                        {#if flagCounts.filtered > 0}
                            <span class="settings-filter-count">{flagCounts.filtered} game{flagCounts.filtered === 1 ? '' : 's'}</span>
                        {/if}
                    </span>
                    <span class="settings-toggle-desc">Hide games flagged as filtered (political themes, personal preference, etc.).</span>
                </div>
                <div class="settings-toggle-switch">
                    <input type="checkbox" checked={!settings.showFiltered}
                           onchange={(e) => onToggle('showFiltered', e.currentTarget.checked, true)}>
                    <span class="settings-toggle-track"></span>
                </div>
            </label>

            <label class="settings-toggle-row">
                <div class="settings-toggle-text">
                    <span class="settings-toggle-label">Hide Software &amp; Tools</span>
                    <span class="settings-toggle-desc">Hide apps flagged as Software / Tool (e.g. Wallpaper Engine) so they don't clutter your game collection.</span>
                </div>
                <div class="settings-toggle-switch">
                    <input type="checkbox" checked={!settings.showSoftware}
                           onchange={(e) => onToggle('showSoftware', e.currentTarget.checked, true)}>
                    <span class="settings-toggle-track"></span>
                </div>
            </label>

            <label class="settings-toggle-row">
                <div class="settings-toggle-text">
                    <span class="settings-toggle-label">Enable Discovery Filters</span>
                    <span class="settings-toggle-desc">Apply the title blocklist to the Discovery page and home page mosaic. Turn off to see all results unfiltered.</span>
                </div>
                <div class="settings-toggle-switch">
                    <input type="checkbox" checked={settings.discoverFiltersEnabled}
                           onchange={(e) => onToggle('discoverFiltersEnabled', e.currentTarget.checked)}>
                    <span class="settings-toggle-track"></span>
                </div>
            </label>

            <label class="settings-toggle-row">
                <div class="settings-toggle-text">
                    <span class="settings-toggle-label">Hide Adult-Only Content</span>
                    <span class="settings-toggle-desc">Hide games Steam flags as Adult Only Sexual Content from Discovery and the home page mosaic. Lighter content (nudity in an otherwise mainstream title, e.g. Cyberpunk 2077) isn't affected.</span>
                </div>
                <div class="settings-toggle-switch">
                    <input type="checkbox" checked={settings.hideAdultContent}
                           onchange={(e) => onToggle('hideAdultContent', e.currentTarget.checked)}>
                    <span class="settings-toggle-track"></span>
                </div>
            </label>

            <div class="settings-blocklist-row">
                <div class="settings-toggle-text">
                    <span class="settings-toggle-label">
                        Discovery Title Filter
                        {#if (settings.titleBlocklist?.length ?? 0) > 0}
                            <span class="settings-filter-count">{settings.titleBlocklist!.length} term{settings.titleBlocklist!.length === 1 ? '' : 's'}</span>
                        {/if}
                    </span>
                    <span class="settings-toggle-desc">Hide games whose titles contain any of these words or phrases from Discovery and the home page mosaic.</span>
                </div>
                <button class="settings-reveal-btn" onclick={() => showBlocklist = !showBlocklist}>
                    {showBlocklist ? 'Hide' : 'Manage'}
                </button>
            </div>
            {#if showBlocklist}
            <div class="settings-blocklist-panel">
                {#if settings.titleBlocklist?.length}
                    <div class="settings-blocklist-tags">
                        {#each settings.titleBlocklist as term, i}
                            <span class="settings-blocklist-tag">
                                {term}
                                <button class="settings-blocklist-tag-remove" onclick={() => removeTerm(i)} aria-label="Remove {term}">×</button>
                            </span>
                        {/each}
                    </div>
                {:else}
                    <p class="settings-blocklist-empty">No terms yet. Add one below.</p>
                {/if}
                <div class="settings-blocklist-add-row">
                    <input
                        class="settings-blocklist-input"
                        type="text"
                        placeholder="Add a word or phrase…"
                        bind:value={newTerm}
                        onkeydown={(e) => { if (e.key === 'Enter') addTerm() }}
                    >
                    <button class="settings-blocklist-add-btn" onclick={addTerm}>Add</button>
                </div>
            </div>
            {/if}
        </section>

        <section class="settings-section">
            <h2 class="settings-section-title">Wishlist</h2>
            <label class="settings-toggle-row">
                <div class="settings-toggle-text">
                    <span class="settings-toggle-label">Hide Unavailable Games</span>
                    <span class="settings-toggle-desc">Hide wishlist items that are no longer available on the Steam store.</span>
                </div>
                <div class="settings-toggle-switch">
                    <input type="checkbox" checked={settings.hideUnavailable}
                           onchange={(e) => onToggle('hideUnavailable', e.currentTarget.checked)}>
                    <span class="settings-toggle-track"></span>
                </div>
            </label>
        </section>
    </div>
{/if}

// react-native/src/app/(drawer)/settings.tsx
import { useQuery } from '@tanstack/react-query'
import { useEffect, useMemo, useState } from 'react'
import { Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native'

import { getApiHost, setApiHost } from '@/api/config'
import { getFlags } from '@/api/flags'
import { getSettings, patchSettings } from '@/api/settings'
import { setCachedBlocklist } from '@/storage/discBlocklist'
import { colors, fonts, radius, spacing } from '@/theme/tokens'
import type { Settings } from 'gaming-journal-contracts/settings'

// Port of Settings.svelte (account/settings.md) — Content Filters + Wishlist sections — appended
// below this screen's PRE-EXISTING "API Host" section (Phase 0 infrastructure: the Tailscale/LAN
// address this RN app talks to). These are genuinely different concerns with no shared web
// equivalent — the web app IS the server, so it never needed a "which server" setting — but they
// share the same `/settings` drawer route, and splitting them into two differently-named drawer
// entries would be a more confusing nav than one screen with two sections. Kept as one screen.
//
// Optimistic update with rollback on every toggle (`onToggle`/`saveBlocklist` in the real
// component) — update local state immediately, PATCH, revert to the pre-change value on failure.
//
// **Unified toggle polarity — ON = hide, OFF = show, across every content filter.** Some settings
// are stored as "show X" (true = visible), so those rows pass `invert=true` to `onToggle` and the
// switch renders the negation of the stored value (`value={!settings.showChildLocked}`). Settings
// already stored as "hide X" (e.g. `hideUnavailable`, true = hidden) pass no invert flag. This
// mirrors the web `Settings.svelte`, whose `onToggle(key, checked, invert)` uses the same rule.
//
// **Dual write for the title blocklist, replicated exactly**: every blocklist change PATCHes
// `/api/settings` AND mirrors the full list to the AsyncStorage key `disc-title-blocklist` (the RN
// equivalent of the web's `localStorage` key of the same name) via `setCachedBlocklist()` — the
// Discover screen (this phase's earlier item) reads that mirror for an instant initial filter
// state before its own settings fetch resolves, matching the real app's two-storage-writes-per-
// change design rather than simplifying to a single PATCH.
export default function SettingsScreen() {
    const [host, setHost] = useState('')
    const [hostSaved, setHostSaved] = useState(false)

    useEffect(() => { getApiHost().then(setHost) }, [])

    async function handleSaveHost() {
        await setApiHost(host)
        setHostSaved(true)
        setTimeout(() => setHostSaved(false), 1500)
    }

    const settingsQuery = useQuery({ queryKey: ['settings'], queryFn: getSettings })
    const flagsQuery = useQuery({ queryKey: ['flags'], queryFn: getFlags })

    const [settings, setSettings] = useState<Partial<Settings>>({})
    const [showBlocklist, setShowBlocklist] = useState(false)
    const [newTerm, setNewTerm] = useState('')

    useEffect(() => {
        if (settingsQuery.data) setSettings(settingsQuery.data)
    }, [settingsQuery.data])

    const flagCounts = useMemo(() => {
        const flags = Object.values(flagsQuery.data ?? {})
        return {
            childLocked: flags.filter(f => f?.childLock).length,
            filtered: flags.filter(f => f?.filtered).length,
        }
    }, [flagsQuery.data])

    // Every content-filter toggle in the UI means the same thing: ON = hide, OFF = show.
    // Some underlying settings are stored the opposite way ("show X" = true means visible),
    // so those rows pass invert=true — the UI switch is the negation of the stored value.
    async function onToggle(key: keyof Settings, checked: boolean, invert = false) {
        const prev = settings[key]
        const nextValue = invert ? !checked : checked
        setSettings(s => ({ ...s, [key]: nextValue }))
        try {
            await patchSettings({ [key]: nextValue })
        } catch {
            setSettings(s => ({ ...s, [key]: prev }))
        }
    }

    async function saveBlocklist(list: string[]) {
        const prev = settings.titleBlocklist
        setSettings(s => ({ ...s, titleBlocklist: list }))
        try {
            await patchSettings({ titleBlocklist: list })
            await setCachedBlocklist(list)
        } catch {
            setSettings(s => ({ ...s, titleBlocklist: prev }))
        }
    }

    function addTerm() {
        const term = newTerm.trim().toLowerCase()
        if (!term) return
        saveBlocklist([...(settings.titleBlocklist ?? []), term])
        setNewTerm('')
    }

    function removeTerm(i: number) {
        saveBlocklist((settings.titleBlocklist ?? []).filter((_, idx) => idx !== i))
    }

    const blocklist = settings.titleBlocklist ?? []

    return (
        <ScrollView style={styles.container} contentContainerStyle={styles.content}>
            <Text style={styles.pageTitle}>Settings</Text>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>API Host</Text>
                <Text style={styles.sectionDesc}>
                    Tailscale hostname or LAN IP for the gaming-journal server, e.g. http://192.168.86.65:8061
                </Text>
                <TextInput
                    value={host}
                    onChangeText={setHost}
                    autoCapitalize="none"
                    autoCorrect={false}
                    placeholder="http://192.168.86.65:8061"
                    placeholderTextColor={colors.textMuted}
                    style={styles.hostInput}
                />
                <Pressable onPress={handleSaveHost} style={styles.hostSaveBtn}>
                    <Text style={styles.hostSaveBtnText}>{hostSaved ? 'Saved' : 'Save'}</Text>
                </Pressable>
            </View>

            {settingsQuery.isLoading ? (
                <Text style={styles.loadingText}>Loading settings…</Text>
            ) : settingsQuery.isError ? (
                <Text style={styles.errorText}>Failed to load settings.</Text>
            ) : (
                <>
                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Content Filters</Text>
                        <Text style={styles.sectionDesc}>
                            Every toggle here works the same way: on hides, off shows. Games flagged as Child Lock or Filtered are hidden by default — turn a toggle off to reveal them.
                        </Text>

                        <ToggleRow
                            label="Hide Child Locked Games"
                            count={flagCounts.childLocked}
                            desc="Hide games flagged with the child lock from library, wishlist, and all other lists."
                            value={!settings.showChildLocked}
                            onChange={(v) => onToggle('showChildLocked', v, true)}
                        />
                        <ToggleRow
                            label="Hide Filtered Games"
                            count={flagCounts.filtered}
                            desc="Hide games flagged as filtered (political themes, personal preference, etc.)."
                            value={!settings.showFiltered}
                            onChange={(v) => onToggle('showFiltered', v, true)}
                        />
                        <ToggleRow
                            label="Enable Discovery Filters"
                            desc="Apply the title blocklist to the Discovery page and home page mosaic. Turn off to see all results unfiltered."
                            value={!!settings.discoverFiltersEnabled}
                            onChange={(v) => onToggle('discoverFiltersEnabled', v)}
                        />

                        <View style={styles.blocklistRow}>
                            <View style={styles.toggleText}>
                                <Text style={styles.toggleLabel}>
                                    Discovery Title Filter
                                    {blocklist.length > 0 && <Text style={styles.filterCount}>  {blocklist.length} term{blocklist.length === 1 ? '' : 's'}</Text>}
                                </Text>
                                <Text style={styles.toggleDesc}>Hide games whose titles contain any of these words or phrases from Discovery and the home page mosaic.</Text>
                            </View>
                            <Pressable style={styles.revealBtn} onPress={() => setShowBlocklist(v => !v)}>
                                <Text style={styles.revealBtnText}>{showBlocklist ? 'Hide' : 'Manage'}</Text>
                            </Pressable>
                        </View>

                        {showBlocklist && (
                            <View style={styles.blocklistPanel}>
                                {blocklist.length > 0 ? (
                                    <View style={styles.blocklistTags}>
                                        {blocklist.map((term, i) => (
                                            <View key={`${term}-${i}`} style={styles.blocklistTag}>
                                                <Text style={styles.blocklistTagText}>{term}</Text>
                                                <Pressable onPress={() => removeTerm(i)} hitSlop={6}>
                                                    <Text style={styles.blocklistTagRemove}>×</Text>
                                                </Pressable>
                                            </View>
                                        ))}
                                    </View>
                                ) : (
                                    <Text style={styles.blocklistEmpty}>No terms yet. Add one below.</Text>
                                )}
                                <View style={styles.blocklistAddRow}>
                                    <TextInput
                                        style={styles.blocklistInput}
                                        placeholder="Add a word or phrase…"
                                        placeholderTextColor={colors.textMuted}
                                        value={newTerm}
                                        onChangeText={setNewTerm}
                                        onSubmitEditing={addTerm}
                                        autoCapitalize="none"
                                    />
                                    <Pressable style={styles.blocklistAddBtn} onPress={addTerm}>
                                        <Text style={styles.blocklistAddBtnText}>Add</Text>
                                    </Pressable>
                                </View>
                            </View>
                        )}
                    </View>

                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Wishlist</Text>
                        <ToggleRow
                            label="Hide Unavailable Games"
                            desc="Hide wishlist items that are no longer available on the Steam store."
                            value={!!settings.hideUnavailable}
                            onChange={(v) => onToggle('hideUnavailable', v)}
                        />
                    </View>
                </>
            )}
        </ScrollView>
    )
}

function ToggleRow({
    label, desc, value, onChange, count,
}: {
    label: string
    desc: string
    value: boolean
    onChange: (v: boolean) => void
    count?: number
}) {
    return (
        <View style={styles.toggleRow}>
            <View style={styles.toggleText}>
                <Text style={styles.toggleLabel}>
                    {label}
                    {!!count && <Text style={styles.filterCount}>  {count} game{count === 1 ? '' : 's'}</Text>}
                </Text>
                <Text style={styles.toggleDesc}>{desc}</Text>
            </View>
            <Switch
                value={value}
                onValueChange={onChange}
                trackColor={{ false: colors.bgHover, true: colors.accentBg }}
                thumbColor={value ? colors.accent : colors.textMuted}
            />
        </View>
    )
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.bg },
    content: { padding: spacing.md, gap: spacing.lg, paddingBottom: spacing.xxl },
    loadingText: { color: colors.textMuted, fontFamily: fonts.ui, padding: spacing.lg },
    errorText: { color: colors.text, fontFamily: fonts.ui, textAlign: 'center', margin: spacing.lg },
    pageTitle: { color: colors.text, fontFamily: fonts.title, fontSize: 22 },
    section: { gap: spacing.sm },
    sectionTitle: { color: colors.text, fontFamily: fonts.title, fontSize: 16 },
    sectionDesc: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 12, lineHeight: 17 },
    hostInput: { borderWidth: 1, borderColor: colors.border, borderRadius: radius, padding: spacing.sm, color: colors.text, fontFamily: fonts.ui },
    hostSaveBtn: { backgroundColor: colors.accent, borderRadius: radius, padding: spacing.sm, alignItems: 'center' },
    hostSaveBtnText: { color: colors.bg, fontFamily: fonts.uiBold },
    toggleRow: {
        flexDirection: 'row', alignItems: 'center', gap: spacing.md,
        paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border,
    },
    toggleText: { flex: 1, gap: 2 },
    toggleLabel: { color: colors.text, fontFamily: fonts.uiBold, fontSize: 13 },
    toggleDesc: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 11, lineHeight: 15 },
    filterCount: { color: colors.accent, fontFamily: fonts.ui, fontSize: 11 },
    blocklistRow: {
        flexDirection: 'row', alignItems: 'center', gap: spacing.md,
        paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border,
    },
    revealBtn: { paddingHorizontal: spacing.sm, paddingVertical: 6, borderRadius: radius, backgroundColor: colors.bgHover },
    revealBtnText: { color: colors.text, fontFamily: fonts.uiBold, fontSize: 12 },
    blocklistPanel: { gap: spacing.sm, paddingTop: spacing.xs },
    blocklistTags: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
    blocklistTag: {
        flexDirection: 'row', alignItems: 'center', gap: 6,
        backgroundColor: colors.bgHover, borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: 4,
    },
    blocklistTagText: { color: colors.text, fontFamily: fonts.ui, fontSize: 12 },
    blocklistTagRemove: { color: colors.textMuted, fontSize: 14 },
    blocklistEmpty: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 12, fontStyle: 'italic' },
    blocklistAddRow: { flexDirection: 'row', gap: spacing.xs },
    blocklistInput: {
        flex: 1, backgroundColor: colors.bgHover, borderWidth: 1, borderColor: colors.border, borderRadius: radius,
        color: colors.text, fontFamily: fonts.ui, fontSize: 13, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm,
    },
    blocklistAddBtn: { paddingHorizontal: spacing.md, justifyContent: 'center', borderRadius: radius, backgroundColor: colors.accentBg, borderWidth: 1, borderColor: colors.borderAct },
    blocklistAddBtnText: { color: colors.accent, fontFamily: fonts.uiBold, fontSize: 13 },
})
