// react-native/src/components/game/GameHero.tsx
import { router } from 'expo-router'
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native'

import { HeroCrossfade } from '@/components/shared/HeroCrossfade'
import { colors, fonts, spacing } from '@/theme/tokens'
import { fmtHours, scoreColor } from '@/utils/gameRender'
import type { CommunityReviews } from 'gaming-journal-contracts/communityReviews'
import type { GameDetail } from 'gaming-journal-contracts/gameDetail'
import type { ProtonDbRaw } from 'gaming-journal-contracts/protondb'

// Port of GameHero.svelte. Background slideshow reuses the shared HeroCrossfade component in its
// "precomputed frames" mode (same one built for the Franchise detail hero) — game.media.screenshots
// is already available from Phase 1, no per-appid probing needed. Interval/fade match GameHero's
// own constants (6000ms/1500ms), NOT Favorites' (14000ms/1500ms) or Franchise's (6000ms/1800ms).
// Deliberately NOT ported: the 20% chance "Ken Burns" background-position pan over 10s — same
// category of deliberate cosmetic simplification as Favorites'/Franchise's hero (crossfade itself,
// the actual documented behavior, is exact; the pan is decoration on top).
// Also NOT ported: the update-badge phase-2-loading micro-animation (1200ms hold + 400ms fade) —
// each RN section already shows its own inline loading state via useQuery, so a second floating
// "still loading" indicator duplicates that signal rather than adding real information.
export function GameHero({
    game, communityReviews, protonTier, apiHost,
}: {
    game: GameDetail
    communityReviews: CommunityReviews | null | undefined
    protonTier: ProtonDbRaw | null | undefined
    apiHost: string | undefined
}) {
    const store = game.store
    const screenshots = game.media?.screenshots ?? []
    const frames = apiHost
        ? (screenshots.length > 0 ? screenshots : [game.media?.background, game.media?.header].filter((s): s is string => !!s))
            .map(p => `${apiHost}${p}`)
        : []

    const steamRatio = communityReviews?.summary?.ratio ?? null
    const mc = store?.metacritic
    const mcScore = typeof mc === 'number' ? mc : (mc?.score ?? null)

    const playerHours = (game.playtimeMinutes ?? 0) / 60
    const hltb = game.hltb
    const itad = game.itad

    const genres = store?.genres ?? []
    const catWhitelist = ['Single-player', 'Multi-player', 'Co-op', 'Online Co-op', 'Steam Achievements', 'Steam Cloud', 'Full controller support']
    const cats = (store?.categories ?? []).filter(c => catWhitelist.includes(c))
    const badges = [...genres, ...cats].slice(0, 7)

    const releaseLabel = (store?.categories ?? []).includes('Early Access') ? 'Early Access Since' : 'Released'
    const platStr = [
        store?.platforms?.windows && 'Windows',
        store?.platforms?.mac && 'macOS',
        store?.platforms?.linux && 'Linux',
    ].filter(Boolean).join(' · ')

    const developer = store?.developers?.[0]
    const publisher = store?.publishers?.[0] && store.publishers[0] !== developer ? store.publishers[0] : null

    return (
        <View style={styles.hero}>
            {frames.length > 0 && <HeroCrossfade frames={frames} intervalMs={6000} fadeMs={1500} />}
            <View style={styles.scrim} />
            <View style={styles.content}>
                <Pressable onPress={() => router.push('/' as never)}>
                    <Text style={styles.breadcrumb}>Home / <Text style={styles.breadcrumbCurrent}>{game.name}</Text></Text>
                </Pressable>
                <Text style={styles.title} numberOfLines={2}>{game.name}</Text>

                <View style={styles.chipsRow}>
                    <ScoreChip label="Steam" score={steamRatio} display={steamRatio != null ? `${Math.round(steamRatio)}%` : ''} />
                    <ScoreChip label="Metacritic" score={mcScore} display={mcScore != null ? String(mcScore) : ''} />
                    <ScoreChip label="OpenCritic" score={null} display="" />
                    {protonTier?.tier && (
                        <Pressable
                            style={styles.protonBadge}
                            onPress={() => Linking.openURL(`https://www.protondb.com/app/${game.appid}`)}
                        >
                            <Text style={styles.protonBadgeText}>Proton: {protonTier.tier}</Text>
                        </Pressable>
                    )}
                </View>

                <View style={styles.statsPanel}>
                    <StatRow label="Played" value={playerHours > 0 ? fmtHours(playerHours) : 'Not played'} />
                    {hltb?.matched && hltb.gameplayMain != null && <StatRow label="Main Story" value={fmtHours(hltb.gameplayMain)} />}
                    {hltb?.matched && hltb.gameplayMainExtra != null && <StatRow label="Main + Extras" value={fmtHours(hltb.gameplayMainExtra)} />}
                    {hltb?.matched && hltb.gameplayCompletionist != null && <StatRow label="Completionist" value={fmtHours(hltb.gameplayCompletionist)} />}
                    {itad?.bestPrice ? (
                        <StatRow
                            label="Best Price"
                            value={`$${itad.bestPrice.price?.toFixed(2)} · ${itad.bestPrice.store}${itad.bestPrice.cut ? ` -${itad.bestPrice.cut}%` : ''}`}
                        />
                    ) : store?.isFree ? (
                        <StatRow label="Best Price" value="Free to Play" />
                    ) : store?.price?.final_formatted ? (
                        <StatRow label="Best Price" value={`${store.price.final_formatted} · Steam`} />
                    ) : null}
                    {itad?.historicalLow && (
                        <StatRow
                            label="All-Time Low"
                            value={`$${itad.historicalLow.price?.toFixed(2)} · ${itad.historicalLow.store} (${itad.historicalLow.date?.slice(0, 4)})`}
                        />
                    )}
                    {store?.releaseDate && <StatRow label={releaseLabel} value={store.releaseDate} />}
                    {developer && <StatRow label="Developer" value={developer} />}
                    {publisher && <StatRow label="Publisher" value={publisher} />}
                    {platStr && <StatRow label="Platforms" value={platStr} />}
                    <Pressable onPress={() => Linking.openURL(`https://store.steampowered.com/app/${game.appid}`)}>
                        <StatRow label="Steam ID" value={`${game.appid} ↗`} />
                    </Pressable>
                </View>

                {badges.length > 0 && (
                    <View style={styles.badgeRow}>
                        {badges.map(b => <Text key={b} style={styles.badge}>{b}</Text>)}
                    </View>
                )}

                <View style={styles.actionsRow}>
                    <Pressable style={styles.actionBtn} onPress={() => router.push(`/journal/${game.appid}` as never)}>
                        <Text style={styles.actionBtnText}>Open Journal</Text>
                    </Pressable>
                    <Pressable style={styles.actionBtn} onPress={() => router.push(`/community/${game.appid}` as never)}>
                        <Text style={styles.actionBtnText}>Community</Text>
                    </Pressable>
                </View>
            </View>
        </View>
    )
}

function ScoreChip({ label, score, display }: { label: string; score: number | null; display: string }) {
    const c = scoreColor(score)
    return (
        <View style={[styles.chip, c && { backgroundColor: c.bg }]}>
            <Text style={styles.chipLabel}>{label}</Text>
            <Text style={[styles.chipValue, { color: c?.clr ?? colors.textMuted }]}>{display || '—'}</Text>
        </View>
    )
}

function StatRow({ label, value }: { label: string; value: string }) {
    return (
        <View style={styles.statRow}>
            <Text style={styles.statLabel}>{label}</Text>
            <Text style={styles.statValue}>{value}</Text>
        </View>
    )
}

const styles = StyleSheet.create({
    hero: { minHeight: 260, backgroundColor: colors.bgRaised, overflow: 'hidden' },
    scrim: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(13,11,9,0.45)' },
    content: { padding: spacing.md, gap: spacing.sm },
    breadcrumb: { color: 'rgba(237,233,223,0.5)', fontFamily: fonts.ui, fontSize: 11 },
    breadcrumbCurrent: { color: 'rgba(237,233,223,0.85)' },
    title: { color: '#fff', fontFamily: fonts.title, fontSize: 22, textShadowColor: 'rgba(0,0,0,0.6)', textShadowRadius: 4 },
    chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
    chip: { backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 4, paddingHorizontal: spacing.sm, paddingVertical: 4, flexDirection: 'row', alignItems: 'center', gap: 4 },
    chipLabel: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 10, textTransform: 'uppercase' },
    chipValue: { fontFamily: fonts.uiBold, fontSize: 12 },
    protonBadge: { backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 4, paddingHorizontal: spacing.sm, paddingVertical: 4 },
    protonBadgeText: { color: colors.text, fontFamily: fonts.uiBold, fontSize: 11, textTransform: 'capitalize' },
    statsPanel: { backgroundColor: 'rgba(0,0,0,0.35)', borderRadius: 6, padding: spacing.sm, gap: 4, maxWidth: 420 },
    statRow: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm },
    statLabel: { color: 'rgba(255,255,255,0.55)', fontFamily: fonts.ui, fontSize: 11 },
    statValue: { color: colors.text, fontFamily: fonts.uiBold, fontSize: 11, flexShrink: 1, textAlign: 'right' },
    badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    badge: {
        color: 'rgba(255,255,255,0.7)', fontFamily: fonts.ui, fontSize: 10,
        backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3,
    },
    actionsRow: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs },
    actionBtn: { backgroundColor: colors.accentBg, borderWidth: 1, borderColor: colors.borderAct, borderRadius: 4, paddingHorizontal: spacing.md, paddingVertical: spacing.xs },
    actionBtnText: { color: colors.accent, fontFamily: fonts.uiBold, fontSize: 12 },
})

// src/lib/svelte/game/GameHero.svelte
<script>
    import { onMount, onDestroy } from 'svelte'
    import { escapeHtml } from '../../js/utils.js'
    import { gameBackLabel, gameBackPath } from '../../js/router.js'
    import { scoreChip, fmtHours, renderGdpPrices } from '../../js/views/game-render.js'

    let { game, communityReviews, protonData, itad, hltb, bgPending = 0 } = $props()

    const SVG_AWARD = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526"/><circle cx="12" cy="8" r="6"/></svg>`
    const SVG_SYNC  = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/></svg>`

    // Background slideshow
    let bgAEl = $state(null)
    let bgBEl = $state(null)
    let timer = null

    onMount(() => {
        if (!bgAEl || !bgBEl) return
        const shots = game?.media?.screenshots ?? []
        const candidates = shots.length > 0 ? shots : [game?.media?.background].filter(Boolean)
        if (candidates.length < 2) return

        Promise.all(candidates.map(url => new Promise(resolve => {
            const img = new Image()
            img.onload  = () => resolve(url)
            img.onerror = () => resolve(null)
            img.src = url
        }))).then(loaded => {
            const frames = loaded.filter(Boolean)
            if (frames.length < 2) return

            for (let i = frames.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [frames[i], frames[j]] = [frames[j], frames[i]]
            }

            const INTERVAL = 6_000, PAN_DUR = 10_000
            const randDir = () => Math.random() < 0.5 ? 'top' : 'bottom'
            const willPan = () => Math.random() < 0.2

            const applyTransition = (el, pan) => {
                requestAnimationFrame(() => requestAnimationFrame(() => {
                    el.style.transition = pan ? `opacity 1.5s ease, background-position ${PAN_DUR}ms linear` : 'opacity 1.5s ease'
                    if (pan) el.style.backgroundPosition = `center ${randDir()}`
                }))
            }

            applyTransition(bgAEl, willPan())
            let idx = 1, showingA = true

            timer = setInterval(() => {
                if (!document.contains(bgAEl)) { clearInterval(timer); return }
                const url      = frames[idx % frames.length]
                const incoming = showingA ? bgBEl : bgAEl
                const outgoing = showingA ? bgAEl : bgBEl
                const pan      = willPan()
                idx++
                incoming.style.transition         = 'none'
                incoming.style.backgroundImage    = `url('${url}')`
                incoming.style.backgroundPosition = 'center center'
                incoming.style.opacity            = '0'
                requestAnimationFrame(() => requestAnimationFrame(() => {
                    if (!document.contains(bgAEl)) return
                    incoming.style.transition = pan ? `opacity 1.5s ease, background-position ${PAN_DUR}ms linear` : 'opacity 1.5s ease'
                    incoming.style.opacity    = '1'
                    if (pan) incoming.style.backgroundPosition = `center ${randDir()}`
                    outgoing.style.opacity = '0'
                }))
                showingA = !showingA
            }, INTERVAL)
        })
    })

    onDestroy(() => { if (timer) clearInterval(timer) })

    let screenshots  = $derived(game?.media?.screenshots ?? [])
    let initBg       = $derived(screenshots[0] ?? game?.media?.background ?? game?.media?.header ?? '')
    let logoUrl      = $derived(game?.media?.logo ?? '')
    let desc         = $derived(game?.store?.description ?? '')
    let steamRatio   = $derived(communityReviews?.summary?.ratio ?? null)
    let mcData       = $derived(game?.store?.metacritic)
    let mcScore      = $derived(mcData?.score ?? (typeof mcData === 'number' ? mcData : null))
    let playerHours  = $derived((game?.playtimeMinutes ?? 0) / 60)

    let hltbRows = $derived(
        hltb?.matched ? [
            hltb.gameplayMain          != null && { label: 'Main Story',    h: hltb.gameplayMain },
            hltb.gameplayMainExtra     != null && { label: 'Main + Extras', h: hltb.gameplayMainExtra },
            hltb.gameplayCompletionist != null && { label: 'Completionist', h: hltb.gameplayCompletionist },
        ].filter(Boolean) : []
    )

    let tags = $derived.by(() => {
        const genres = game?.store?.genres ?? []
        const cats = (game?.store?.categories ?? []).filter(c =>
            ['Single-player', 'Multi-player', 'Co-op', 'Online Co-op', 'Steam Achievements', 'Steam Cloud', 'Full controller support'].includes(c)
        )
        return [...genres, ...cats].slice(0, 7)
    })

    let plat    = $derived(game?.store?.platforms)
    let platStr = $derived(plat ? [plat.windows && 'Windows', plat.mac && 'macOS', plat.linux && 'Linux'].filter(Boolean).join(' · ') : '')

    let protonTier = $derived(protonData?.tier)
    let protonCap  = (s) => s ? s.charAt(0).toUpperCase() + s.slice(1) : null
</script>

<section class="game-hero" id="game-sec-hero">
    <div class="game-hero-bg game-hero-bg--a" bind:this={bgAEl} style={initBg ? `background-image:url('${initBg}')` : ''}></div>
    <div class="game-hero-bg game-hero-bg--b" bind:this={bgBEl}></div>
    <nav class="game-hero-nav">
        <a href={gameBackPath()} class="game-back-link">&#8592; {gameBackLabel()}</a>
    </nav>
    <div class="game-hero-body">
        <div class="game-hero-left">
            <div class="game-hero-spacer"></div>
            {#if logoUrl}
                <img class="game-hero-logo" src={logoUrl} alt="" onerror={(e) => { e.currentTarget.style.display = 'none' }}>
            {/if}
            <h1 class="game-hero-title">{game?.name ?? ''}</h1>
            {#if desc}<p class="game-hero-desc">{desc}</p>{/if}
            {#if tags.length > 0}
                <div class="game-hero-badges">
                    {#each tags as tag}
                        <span class="game-badge">{tag}</span>
                    {/each}
                </div>
            {/if}
        </div>
        <div class="game-hero-right">
            <div class="game-data-panel">
                <div class="game-panel-badges">
                    {#if bgPending > 0}
                        <div class="update-badge">
                            <span class="update-badge-count">{bgPending}</span>
                            <span class="update-badge-icon">{@html SVG_SYNC}</span>
                            <span class="update-badge-sub">Updating</span>
                        </div>
                    {/if}
                    {#if protonTier}
                        <a class="proton-badge proton-badge--{protonTier}" href="https://www.protondb.com/app/{game?.appid}" target="_blank" rel="noopener noreferrer" title="ProtonDB — {protonCap(protonTier)}">
                            <span class="proton-badge-tier">{protonCap(protonTier)}</span>
                            <span class="proton-badge-icon">{@html SVG_AWARD}</span>
                            <span class="proton-badge-sub">Linux / Proton</span>
                        </a>
                    {/if}
                </div>

                <!-- Score row -->
                <div class="gdp-score-row">
                    {@html scoreChip('Steam', steamRatio, steamRatio != null ? Math.round(steamRatio) + '%' : null, 'gdp-steam-chip')}
                    {@html scoreChip('OpenCritic', null, null)}
                    {@html scoreChip('Metacritic', mcScore, mcScore)}
                </div>

                <!-- Playtime -->
                <div class="gdp-row">
                    <span class="gdp-label">Played</span>
                    <span class="gdp-value">{playerHours > 0 ? fmtHours(playerHours) : 'Not played'}</span>
                </div>

                <!-- HLTB rows -->
                {#if hltbRows.length > 0}
                    <div class="gdp-divider"></div>
                    {#each hltbRows as row}
                        <div class="gdp-row">
                            <span class="gdp-label">{row.label}</span>
                            <span class="gdp-value">{fmtHours(row.h)}</span>
                        </div>
                    {/each}
                {/if}

                <!-- ITAD prices -->
                {@html renderGdpPrices(itad, game)}

                <!-- Release / meta -->
                <div class="gdp-divider"></div>
                {#if game?.store?.releaseDate}
                    {@const rs = game?.store?.categories?.includes('Early Access') ? 'early_access' : 'released'}
                    <div class="gdp-row">
                        <span class="gdp-label">{rs === 'early_access' ? 'Early Access Since' : 'Released'}</span>
                        <span class="gdp-value">{game.store.releaseDate}</span>
                    </div>
                {/if}
                {#if game?.store?.developers?.length}
                    <div class="gdp-row">
                        <span class="gdp-label">Developer</span>
                        <span class="gdp-value">{game.store.developers[0]}</span>
                    </div>
                {/if}
                {#if game?.store?.publishers?.length && game.store.publishers[0] !== game.store.developers?.[0]}
                    <div class="gdp-row">
                        <span class="gdp-label">Publisher</span>
                        <span class="gdp-value">{game.store.publishers[0]}</span>
                    </div>
                {/if}
                {#if platStr}
                    <div class="gdp-row">
                        <span class="gdp-label">Platforms</span>
                        <span class="gdp-value">{platStr}</span>
                    </div>
                {/if}
                <div class="gdp-divider"></div>
                <div class="gdp-row">
                    <span class="gdp-label">Steam ID</span>
                    <span class="gdp-value">
                        <a class="gdp-steam-link" href="https://store.steampowered.com/app/{game?.appid}" target="_blank" rel="noopener">{game?.appid} ↗</a>
                    </span>
                </div>

                <div class="game-panel-btns">
                    <a href="/journal/{game?.appid}" class="game-journal-btn">
                        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="flex-shrink:0;vertical-align:middle"><path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><line x1="16" x2="8" y1="13" y2="13"/><line x1="16" x2="8" y1="17" y2="17"/></svg>
                        Open Journal
                    </a>
                    <a href="/community/{game?.appid}" class="game-journal-btn game-community-btn">
                        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="flex-shrink:0;vertical-align:middle"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
                        Community
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
