// react-native/src/app/(drawer)/recommend.tsx
import { Image } from 'expo-image'
import { router } from 'expo-router'
import { useState } from 'react'
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import Animated, { FadeInUp } from 'react-native-reanimated'

import { postRecommend } from '@/api/recommend'
import { RecommendGraph } from '@/components/recommend/RecommendGraph'
import { useApiHost } from '@/hooks/useApiHost'
import { useBreakpoint } from '@/hooks/useBreakpoint'
import { colors, fonts, radius, spacing } from '@/theme/tokens'
import { RECOMMEND_DEPTHS, type RecommendDepth, type RecommendGame, type RecommendQuestion } from 'gaming-journal-contracts/recommend'

const DEPTH_QUESTIONS: Record<RecommendDepth, number> = { shallow: 3, normal: 5, deep: 7 }

type Phase = 'start' | 'playing' | 'results'
type Filter = { type: string; value: string | null }

// Port of recommend/+page.svelte. Two presentations mirroring the web: the desktop tier renders the
// animated SVG node graph (RecommendGraph — radial option nodes, elbow-routed per-type-colored
// edges, center node, result nodes with header art); the phone (mobilePortrait) tier keeps the
// web's own stacked-list fallback. Same state machine + POST /recommend flow drive both; only the
// presentation changes. Tablet-landscape (1440dp) classifies as the desktop tier, so it gets the graph.
export default function RecommendScreen() {
    const apiHostQuery = useApiHost()
    const apiHost = apiHostQuery.data
    const isMobilePortrait = useBreakpoint() === 'mobilePortrait'

    const [depth, setDepth] = useState<RecommendDepth>('normal')
    const [phase, setPhase] = useState<Phase>('start')
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [sequence, setSequence] = useState<string[] | null>(null)
    const [question, setQuestion] = useState<RecommendQuestion | null>(null)
    const [games, setGames] = useState<RecommendGame[] | null>(null)
    const [relaxed, setRelaxed] = useState(false)
    const [stepIndex, setStepIndex] = useState(0)
    // The server is STATELESS: it derives both the narrowed game set (applyFilters(base, filters))
    // and the step position (step = filters.length) from the CUMULATIVE filters array. Native was
    // sending only the single latest answer, so every answer replaced the previous ones, step was
    // stuck at 1, and the question sequence never advanced. Accumulate every answer here.
    const [filters, setFilters] = useState<Filter[]>([])

    async function callRecommend(appliedFilters: Filter[], seq: string[] | null) {
        setLoading(true)
        setError(null)
        try {
            const data = await postRecommend({ depth, sequence: seq ?? undefined, filters: appliedFilters })
            if (seq === null && 'sequence' in data) setSequence(data.sequence)
            if (data.done) {
                setGames(data.games)
                setQuestion(null)
                setRelaxed(data.relaxed ?? false)
                setPhase('results')
            } else {
                setQuestion(data.question)
                setGames(null)
                setPhase('playing')
            }
        } catch (e) {
            setError(e instanceof Error ? e.message : 'Something went wrong')
        } finally {
            setLoading(false)
        }
    }

    function reset(returnToStart: boolean) {
        setSequence(null)
        setQuestion(null)
        setGames(null)
        setRelaxed(false)
        setStepIndex(0)
        setFilters([])
        setError(null)
        if (returnToStart) setPhase('start')
    }

    async function start() {
        reset(false)
        await callRecommend([], null)
    }

    async function handleChoice(type: string, value: string) {
        const next = [...filters, { type, value }]
        setFilters(next)
        setStepIndex(i => i + 1)
        await callRecommend(next, sequence)
    }

    async function handleSkip() {
        if (!question) return
        const next: Filter[] = [...filters, { type: question.type, value: null }]
        setFilters(next)
        setStepIndex(i => i + 1)
        await callRecommend(next, sequence)
    }

    return (
        <View style={styles.container}>
            {/* No in-content title here — the drawer app-bar already shows "Recommend" (matching web,
                which surfaces the page title once). This bar is just the depth/skip/reset controls. */}
            <View style={styles.topbar}>
                <View style={styles.controls}>
                    {phase === 'start' ? (
                        <View style={styles.depthToggle}>
                            {RECOMMEND_DEPTHS.map(d => (
                                <Pressable key={d} style={[styles.depthBtn, depth === d && styles.depthBtnActive]} onPress={() => setDepth(d)}>
                                    <Text style={[styles.depthBtnText, depth === d && styles.depthBtnTextActive]}>{d}</Text>
                                </Pressable>
                            ))}
                        </View>
                    ) : (
                        <Text style={styles.depthBadge}>{depth}</Text>
                    )}
                    {phase === 'playing' && question && (
                        <Pressable style={styles.skipBtn} onPress={handleSkip}>
                            <Text style={styles.skipBtnText}>Skip ›</Text>
                        </Pressable>
                    )}
                    {phase !== 'start' && (
                        <Pressable style={styles.resetBtn} onPress={() => reset(true)}>
                            <Text style={styles.resetBtnText}>↺ Reset</Text>
                        </Pressable>
                    )}
                </View>
            </View>

            {phase === 'playing' && sequence && (
                <View style={styles.progressTrack}>
                    {sequence.map((_, i) => (
                        <View key={i} style={[styles.pip, i < stepIndex && styles.pipDone, i === stepIndex && styles.pipActive]} />
                    ))}
                </View>
            )}

            {phase === 'start' ? (
                <ScrollView style={styles.canvas} contentContainerStyle={styles.canvasContent}>
                    <View style={styles.startCard}>
                        <Text style={styles.startIcon}>◎</Text>
                        <Text style={styles.startTitle}>Find your next game</Text>
                        <Text style={styles.startDesc}>Answer a few questions and we'll pull something from your library.</Text>
                        <View style={styles.depthToggleLg}>
                            {RECOMMEND_DEPTHS.map(d => (
                                <Pressable key={d} style={[styles.depthBtnLg, depth === d && styles.depthBtnActive]} onPress={() => setDepth(d)}>
                                    <Text style={[styles.depthKey, depth === d && styles.depthBtnTextActive]}>{d}</Text>
                                    <Text style={styles.depthDesc}>{DEPTH_QUESTIONS[d]} questions</Text>
                                </Pressable>
                            ))}
                        </View>
                        <Pressable style={styles.startBtn} onPress={start}>
                            <Text style={styles.startBtnText}>Start exploring</Text>
                        </Pressable>
                    </View>
                </ScrollView>
            ) : isMobilePortrait ? (
                // Phone tier: the web's own stacked-list fallback.
                <ScrollView style={styles.canvas} contentContainerStyle={styles.canvasContent}>
                    {error && (
                        <View style={[styles.banner, styles.bannerError]}><Text style={styles.bannerErrorText}>{error}</Text></View>
                    )}
                    {relaxed && (
                        <View style={[styles.banner, styles.bannerRelaxed]}><Text style={styles.bannerRelaxedText}>One filter was loosened to find enough results.</Text></View>
                    )}

                    {loading && <Text style={styles.loadingText}>Thinking…</Text>}

                    {!loading && phase === 'playing' && question && (
                        <View key={stepIndex}>
                            <View style={styles.questionCard}>
                                <Text style={styles.questionType}>{question.type}</Text>
                                <Text style={styles.questionLabel}>{question.label}</Text>
                            </View>
                            <View style={styles.options}>
                                {question.options.map((opt, i) => (
                                    <Animated.View key={opt.value} entering={FadeInUp.delay(i * 65 + 120).duration(350)}>
                                        <Pressable style={styles.option} onPress={() => handleChoice(question.type, opt.value)}>
                                            <Text style={styles.optionLabel}>{opt.label}</Text>
                                            {opt.count > 0 && <Text style={styles.optionCount}>{opt.count}</Text>}
                                        </Pressable>
                                    </Animated.View>
                                ))}
                            </View>
                        </View>
                    )}

                    {!loading && phase === 'results' && games && (
                        <View>
                            <Text style={styles.resultsHd}>Here's what to play</Text>
                            <View style={styles.results}>
                                {games.map((game, i) => (
                                    <Animated.View key={game.appid} entering={FadeInUp.delay(i * 65 + 80).duration(350)}>
                                        <Pressable style={styles.gameRow} onPress={() => router.push(`/game/${game.appid}` as never)}>
                                            {!!apiHost && (
                                                <Image source={{ uri: `${apiHost}${game.header}` }} style={styles.gameImg} contentFit="cover" />
                                            )}
                                            <Text style={styles.gameName} numberOfLines={2}>{game.name}</Text>
                                        </Pressable>
                                    </Animated.View>
                                ))}
                            </View>
                        </View>
                    )}
                </ScrollView>
            ) : (
                // Desktop/tablet tier: the SVG node graph. Banners float over the bottom, as on web.
                <View style={styles.graphContainer}>
                    <RecommendGraph
                        question={question}
                        games={games}
                        loading={loading}
                        stepIndex={stepIndex}
                        onChoice={handleChoice}
                        apiHost={apiHost}
                    />
                    {error && (
                        <View style={styles.bannerFloat}>
                            <View style={[styles.banner, styles.bannerError]}><Text style={styles.bannerErrorText}>{error}</Text></View>
                        </View>
                    )}
                    {relaxed && (
                        <View style={styles.bannerFloat}>
                            <View style={[styles.banner, styles.bannerRelaxed]}><Text style={styles.bannerRelaxedText}>One filter was loosened to find enough results.</Text></View>
                        </View>
                    )}
                </View>
            )}
        </View>
    )
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.bg },
    topbar: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, gap: spacing.sm },
    controls: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, flexWrap: 'wrap' },
    depthToggle: { flexDirection: 'row', borderWidth: 1, borderColor: colors.border, borderRadius: radius, overflow: 'hidden' },
    depthBtn: { paddingHorizontal: spacing.sm, paddingVertical: 5, borderRightWidth: 1, borderRightColor: colors.border },
    depthBtnActive: { backgroundColor: colors.bgRaised },
    depthBtnText: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 11, textTransform: 'capitalize' },
    depthBtnTextActive: { color: colors.accent, fontFamily: fonts.uiBold },
    depthBadge: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 11, textTransform: 'capitalize', borderWidth: 1, borderColor: colors.border, borderRadius: radius, paddingHorizontal: spacing.sm, paddingVertical: 3 },
    skipBtn: { borderWidth: 1, borderColor: colors.border, borderRadius: radius, paddingHorizontal: spacing.sm, paddingVertical: 5 },
    skipBtnText: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 11 },
    resetBtn: { borderWidth: 1, borderColor: colors.border, borderRadius: radius, paddingHorizontal: spacing.sm, paddingVertical: 5 },
    resetBtnText: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 11 },
    progressTrack: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.sm },
    pip: { width: 28, height: 3, borderRadius: 2, backgroundColor: colors.border },
    pipDone: { backgroundColor: 'rgba(201,168,76,0.45)' },
    pipActive: { backgroundColor: colors.accent },
    canvas: { flex: 1 },
    canvasContent: { padding: spacing.md, gap: spacing.sm, flexGrow: 1 },
    graphContainer: { flex: 1, position: 'relative' },
    bannerFloat: { position: 'absolute', bottom: 16, left: 0, right: 0, alignItems: 'center' },
    startCard: { alignItems: 'center', gap: spacing.md, padding: spacing.xl, backgroundColor: colors.bgRaised, borderWidth: 1, borderColor: colors.border, borderRadius: 12, marginTop: spacing.xxl, alignSelf: 'center', maxWidth: 420, width: '100%' },
    startIcon: { color: colors.accent, fontSize: 40 },
    startTitle: { color: colors.text, fontFamily: fonts.title, fontSize: 20, textAlign: 'center' },
    startDesc: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 13, textAlign: 'center', lineHeight: 19 },
    depthToggleLg: { flexDirection: 'row', borderWidth: 1, borderColor: colors.border, borderRadius: radius, overflow: 'hidden' },
    depthBtnLg: { alignItems: 'center', paddingHorizontal: spacing.md, paddingVertical: spacing.sm, gap: 2, borderRightWidth: 1, borderRightColor: colors.border },
    depthKey: { color: colors.textMuted, fontFamily: fonts.uiBold, fontSize: 12, textTransform: 'capitalize' },
    depthDesc: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 10 },
    startBtn: { backgroundColor: colors.accent, borderRadius: radius, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
    startBtnText: { color: '#131210', fontFamily: fonts.uiBold, fontSize: 14 },
    banner: { borderRadius: radius, padding: spacing.sm, alignItems: 'center' },
    bannerError: { backgroundColor: 'rgba(239,68,68,0.12)', borderWidth: 1, borderColor: 'rgba(239,68,68,0.25)' },
    bannerErrorText: { color: '#fca5a5', fontFamily: fonts.ui, fontSize: 12 },
    bannerRelaxed: { backgroundColor: colors.accentBg, borderWidth: 1, borderColor: 'rgba(201,168,76,0.3)' },
    bannerRelaxedText: { color: colors.accent, fontFamily: fonts.ui, fontSize: 12 },
    loadingText: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 13, textAlign: 'center', paddingVertical: spacing.xl },
    questionCard: { backgroundColor: colors.bgRaised, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: spacing.md, gap: 4, marginBottom: spacing.sm },
    questionType: { color: colors.accent, fontFamily: fonts.uiBold, fontSize: 10, textTransform: 'uppercase', letterSpacing: 1 },
    questionLabel: { color: colors.text, fontFamily: fonts.title, fontSize: 16 },
    options: { gap: spacing.sm },
    option: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: spacing.sm, padding: spacing.md, backgroundColor: colors.bgRaised, borderWidth: 1, borderColor: colors.border, borderRadius: 8 },
    optionLabel: { flex: 1, color: colors.text, fontFamily: fonts.ui, fontSize: 14 },
    optionCount: { color: colors.textMuted, fontFamily: fonts.ui, fontSize: 12 },
    resultsHd: { color: colors.textMuted, fontFamily: fonts.uiBold, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1, marginBottom: spacing.sm },
    results: { gap: spacing.sm },
    gameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.sm, backgroundColor: colors.bgRaised, borderWidth: 1, borderColor: colors.border, borderRadius: 8 },
    gameImg: { width: 72, height: 34, borderRadius: 4, backgroundColor: colors.bgHover },
    gameName: { flex: 1, color: colors.text, fontFamily: fonts.uiBold, fontSize: 13 },
})

// src/routes/recommend/+page.svelte
<script lang="ts">
    import { onMount } from 'svelte'
    import RecommendGraph from '$lib/svelte/recommend/RecommendGraph.svelte'
    import type { RecommendQuestion, RecommendGame } from '$lib/svelte/recommend/RecommendGraph.svelte'

    type Depth    = 'shallow' | 'normal' | 'deep'
    type PagePhase = 'start' | 'playing' | 'results'

    // ── State ─────────────────────────────────────────────────────────────────
    let depth     = $state<Depth>('normal')
    let isPhone   = $state(false)
    let phase     = $state<PagePhase>('start')
    let loading   = $state(false)
    let error     = $state<string | null>(null)

    let sequence  = $state<string[] | null>(null)
    let filters   = $state<{ type: string; value: string | null }[]>([])
    let question  = $state<RecommendQuestion | null>(null)
    let games     = $state<RecommendGame[] | null>(null)
    let relaxed   = $state(false)
    let stepIndex = $state(0)

    const DEPTH_LABELS: Record<Depth, string> = {
        shallow: 'Shallow  · 3 questions',
        normal:  'Normal   · 5 questions',
        deep:    'Deep     · 7 questions',
    }

    // ── API ───────────────────────────────────────────────────────────────────
    async function callRecommend(appliedFilters: { type: string; value: string | null }[]) {
        loading = true
        error   = null
        try {
            const res  = await fetch('/relay/api/recommend', {
                method:  'POST',
                headers: { 'content-type': 'application/json' },
                body:    JSON.stringify({ depth, sequence: sequence ?? undefined, filters: appliedFilters }),
            })
            if (!res.ok) throw new Error(`Server error ${res.status}`)
            const data = await res.json()

            if (sequence === null && data.sequence) sequence = data.sequence

            if (data.done) {
                games    = data.games
                question = null
                relaxed  = data.relaxed ?? false
                phase    = 'results'
            } else {
                question = data.question
                games    = null
                phase    = 'playing'
            }
        } catch (e) {
            error = e instanceof Error ? e.message : 'Something went wrong'
        } finally {
            loading = false
        }
    }

    // ── Controls ──────────────────────────────────────────────────────────────
    async function start() {
        reset(false)
        await callRecommend([])
    }

    function reset(returnToStart = true) {
        sequence  = null
        filters   = []
        question  = null
        games     = null
        relaxed   = false
        stepIndex = 0
        error     = null
        if (returnToStart) phase = 'start'
    }

    async function handleChoice(type: string, value: string) {
        const next = [...filters, { type, value }]
        filters   = next
        stepIndex = next.length
        await callRecommend(next)
    }

    async function handleSkip() {
        if (!question) return
        const next = [...filters, { type: question.type, value: null }]
        filters   = next
        stepIndex = next.length
        await callRecommend(next)
    }

    onMount(() => {
        const check = () => { isPhone = window.innerWidth <= 479 }
        check()
        window.addEventListener('resize', check)
        return () => window.removeEventListener('resize', check)
    })
</script>

<div class="recommend-page">
    <!-- ── Top bar ─────────────────────────────────────────────────────────── -->
    <div class="recommend-topbar">
        <div class="recommend-title">
            <span class="recommend-title-icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <circle cx="12" cy="12" r="10"/>
                    <polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/>
                </svg>
            </span>
            Recommendations
        </div>

        <div class="recommend-controls">
            <!-- Depth toggle — only changeable before starting -->
            {#if phase === 'start'}
                <div class="depth-toggle">
                    {#each (['shallow', 'normal', 'deep'] as Depth[]) as d}
                        <button
                            class="depth-btn"
                            class:active={depth === d}
                            onclick={() => depth = d}
                        >{d}</button>
                    {/each}
                </div>
            {:else}
                <span class="depth-badge">{depth}</span>
            {/if}

            {#if phase === 'playing' && question}
                <button class="skip-btn" onclick={handleSkip}>
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="13 17 18 12 13 7"/>
                        <polyline points="6 17 11 12 6 7"/>
                    </svg>
                    Skip
                </button>
            {/if}
            {#if phase !== 'start'}
                <button class="reset-btn" onclick={() => reset(true)}>
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/>
                        <path d="M3 3v5h5"/>
                    </svg>
                    Reset
                </button>
            {/if}
        </div>
    </div>

    <!-- ── Progress bar ───────────────────────────────────────────────────── -->
    {#if phase === 'playing' && sequence}
        <div class="progress-track">
            {#each sequence as _, i}
                <div class="progress-pip" class:done={i < stepIndex} class:active={i === stepIndex}></div>
            {/each}
        </div>
    {/if}

    <!-- ── Canvas area ────────────────────────────────────────────────────── -->
    <div class="recommend-canvas">
        {#if phase === 'start'}
            <!-- Start screen -->
            <div class="start-screen">
                <div class="start-card">
                    <div class="start-icon">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
                            <circle cx="12" cy="12" r="10"/>
                            <polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/>
                        </svg>
                    </div>
                    <h2>Find your next game</h2>
                    <p>Answer a few questions and we'll pull something from your library.</p>

                    <div class="depth-toggle depth-toggle--lg">
                        {#each (['shallow', 'normal', 'deep'] as Depth[]) as d}
                            <button
                                class="depth-btn"
                                class:active={depth === d}
                                onclick={() => depth = d}
                            >
                                <span class="depth-key">{d}</span>
                                <span class="depth-desc">
                                    {d === 'shallow' ? '3 questions' : d === 'normal' ? '5 questions' : '7 questions'}
                                </span>
                            </button>
                        {/each}
                    </div>

                    <button class="start-btn" onclick={start}>Start exploring</button>
                </div>
            </div>
        {:else if isPhone}
            <!-- Mobile portrait: stacked layout -->
            <div class="rec-mobile-stack">
                {#if error}
                    <div class="rec-m-banner rec-m-banner--error">{error}</div>
                {/if}
                {#if relaxed}
                    <div class="rec-m-banner rec-m-banner--relaxed">One filter was loosened to find enough results.</div>
                {/if}
                {#if loading}
                    <div class="rec-m-loading">Thinking…</div>
                {:else if phase === 'playing' && question}
                    {#key stepIndex}
                        <div class="rec-m-question">
                            <span class="rec-m-q-type">{question.type}</span>
                            <p class="rec-m-q-label">{question.label}</p>
                        </div>
                        <div class="rec-m-options">
                            {#each question.options as opt, i}
                                <button
                                    class="rec-m-option"
                                    style="--i:{i}"
                                    onclick={() => handleChoice(question!.type, opt.value)}
                                >
                                    <span class="rec-m-opt-label">{opt.label}</span>
                                    {#if opt.count > 0}
                                        <span class="rec-m-opt-count">{opt.count}</span>
                                    {/if}
                                </button>
                            {/each}
                        </div>
                    {/key}
                {:else if phase === 'results' && games}
                    {#key games}
                        <p class="rec-m-result-hd">Here's what to play</p>
                        <div class="rec-m-results">
                            {#each games as game, i}
                                <a class="rec-m-game" href="/game/{game.appid}" style="--i:{i}">
                                    <img class="rec-m-game-img"
                                         src="/relay/images/steam/games/{game.appid}/header.jpg"
                                         alt=""
                                         onerror={(e) => { (e.currentTarget as HTMLImageElement).style.opacity = '0' }}>
                                    <span class="rec-m-game-name">{game.name}</span>
                                </a>
                            {/each}
                        </div>
                    {/key}
                {/if}
            </div>
        {:else}
            <!-- Desktop/tablet: graph -->
            {#if error}
                <div class="error-banner">{error}</div>
            {/if}

            {#if relaxed}
                <div class="relaxed-banner">One filter was loosened to find enough results.</div>
            {/if}

            <RecommendGraph
                {question}
                {games}
                {loading}
                {stepIndex}
                onChoice={handleChoice}
            />
        {/if}
    </div>
</div>

<style>
    .recommend-page {
        display: flex;
        flex-direction: column;
        height: 100%;
        background: var(--clr-bg);
        color: var(--clr-text);
        overflow: hidden;
    }

    /* ── Top bar ────────────────────────────────────────────────────────────── */
    .recommend-topbar {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 14px 24px 10px;
        border-bottom: 1px solid var(--clr-border);
        flex-shrink: 0;
        gap: 16px;
    }
    .recommend-title {
        display: flex;
        align-items: center;
        gap: 10px;
        font-size: 16px;
        font-weight: 600;
        color: var(--clr-text);
        letter-spacing: -0.01em;
    }
    .recommend-title-icon {
        width: 20px;
        height: 20px;
        color: var(--clr-accent);
        display: flex;
    }
    .recommend-title-icon svg { width: 100%; height: 100%; }

    .recommend-controls {
        display: flex;
        align-items: center;
        gap: 12px;
    }

    /* ── Depth toggle ────────────────────────────────────────────────────────── */
    .depth-toggle {
        display: flex;
        border: 1px solid var(--clr-border);
        border-radius: var(--radius);
        overflow: hidden;
    }
    .depth-btn {
        padding: 6px 14px;
        background: transparent;
        border: none;
        color: var(--clr-text-muted);
        font-size: 13px;
        cursor: pointer;
        transition: background var(--transition), color var(--transition);
        border-right: 1px solid var(--clr-border);
        text-transform: capitalize;
    }
    .depth-btn:last-child { border-right: none; }
    .depth-btn:hover { background: var(--clr-bg-hover); color: var(--clr-text); }
    .depth-btn.active {
        background: var(--clr-bg-raised);
        color: var(--clr-accent);
        font-weight: 600;
    }

    .depth-badge {
        font-size: 12px;
        color: var(--clr-text-muted);
        text-transform: capitalize;
        padding: 4px 10px;
        border: 1px solid var(--clr-border);
        border-radius: var(--radius);
    }

    /* ── Skip button ─────────────────────────────────────────────────────────── */
    .skip-btn {
        display: flex;
        align-items: center;
        gap: 6px;
        padding: 6px 14px;
        background: transparent;
        border: 1px solid var(--clr-border);
        border-radius: var(--radius);
        color: var(--clr-text-muted);
        font-size: 13px;
        cursor: pointer;
        transition: border-color var(--transition), color var(--transition);
    }
    .skip-btn svg { width: 14px; height: 14px; }
    .skip-btn:hover {
        border-color: var(--clr-border-hi);
        color: var(--clr-text);
    }

    /* ── Reset button ────────────────────────────────────────────────────────── */
    .reset-btn {
        display: flex;
        align-items: center;
        gap: 6px;
        padding: 6px 14px;
        background: transparent;
        border: 1px solid var(--clr-border);
        border-radius: var(--radius);
        color: var(--clr-text-muted);
        font-size: 13px;
        cursor: pointer;
        transition: border-color var(--transition), color var(--transition), background var(--transition);
    }
    .reset-btn svg { width: 14px; height: 14px; }
    .reset-btn:hover {
        border-color: var(--clr-accent);
        color: var(--clr-accent);
        background: var(--clr-accent-bg);
    }

    /* ── Progress pips ───────────────────────────────────────────────────────── */
    .progress-track {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 8px;
        padding: 8px 0 4px;
        flex-shrink: 0;
    }
    .progress-pip {
        width: 28px;
        height: 3px;
        border-radius: 2px;
        background: var(--clr-border);
        transition: background 0.3s;
    }
    .progress-pip.done   { background: rgba(201,168,76,0.45); }
    .progress-pip.active { background: var(--clr-accent); }

    /* ── Canvas ───────────────────────────────────────────────────────────────── */
    .recommend-canvas {
        flex: 1;
        position: relative;
        overflow: hidden;
    }

    /* ── Start screen ─────────────────────────────────────────────────────────── */
    .start-screen {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100%;
    }
    .start-card {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 20px;
        padding: 48px 52px;
        background: var(--clr-bg-raised);
        border: 1px solid var(--clr-border);
        border-radius: 12px;
        max-width: 420px;
        text-align: center;
    }
    .start-icon {
        width: 52px;
        height: 52px;
        color: var(--clr-accent);
    }
    .start-icon svg { width: 100%; height: 100%; }
    .start-card h2 {
        margin: 0;
        font-size: 22px;
        font-weight: 700;
        color: var(--clr-text);
        letter-spacing: -0.02em;
        font-family: var(--font-title);
    }
    .start-card p {
        margin: 0;
        font-size: 14px;
        color: var(--clr-text-muted);
        line-height: 1.6;
    }

    .depth-toggle--lg .depth-btn {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 12px 20px;
        gap: 3px;
    }
    .depth-key {
        font-size: 13px;
        font-weight: 600;
        text-transform: capitalize;
    }
    .depth-desc {
        font-size: 11px;
        color: var(--clr-text-muted);
    }
    .depth-btn.active .depth-desc { color: var(--clr-accent); }

    .start-btn {
        padding: 12px 32px;
        background: var(--clr-accent);
        border: none;
        border-radius: var(--radius);
        color: #131210;
        font-size: 15px;
        font-weight: 700;
        cursor: pointer;
        transition: opacity var(--transition), transform var(--transition);
        letter-spacing: 0.01em;
    }
    .start-btn:hover { opacity: 0.88; transform: translateY(-1px); }

    /* ── Banners ──────────────────────────────────────────────────────────────── */
    .error-banner, .relaxed-banner {
        position: absolute;
        bottom: 16px;
        left: 50%;
        transform: translateX(-50%);
        padding: 8px 20px;
        border-radius: var(--radius);
        font-size: 13px;
        z-index: 10;
        white-space: nowrap;
    }
    .error-banner {
        background: rgba(239,68,68,0.12);
        border: 1px solid rgba(239,68,68,0.25);
        color: #fca5a5;
    }
    .relaxed-banner {
        background: var(--clr-accent-bg);
        border: 1px solid rgba(201,168,76,0.3);
        color: var(--clr-accent);
    }

    /* ── Mobile topbar compaction (≤479px) ───────────────────────────────────── */
    @media (max-width: 479px) {
        .recommend-topbar   { padding: 10px 16px; gap: 8px; }
        .recommend-title    { font-size: 14px; gap: 8px; }
        .recommend-title-icon { width: 16px; height: 16px; }
        .recommend-controls { gap: 8px; }
        .depth-btn          { padding: 5px 8px; font-size: 11px; }
        .depth-badge        { font-size: 11px; padding: 3px 8px; }
        .skip-btn, .reset-btn { padding: 5px 8px; font-size: 11px; }
        .skip-btn svg, .reset-btn svg { width: 12px; height: 12px; }

        .start-card { padding: 28px 20px; max-width: calc(100% - 32px); gap: 16px; }
        .start-icon { width: 36px; height: 36px; }
        .start-card h2 { font-size: 18px; }
        .depth-toggle--lg .depth-btn { padding: 10px 12px; }
    }

    /* ── Mobile stack layout ─────────────────────────────────────────────────── */
    @keyframes rec-m-enter {
        from { opacity: 0; transform: translateY(14px) scale(0.97); }
        to   { opacity: 1; transform: translateY(0) scale(1); }
    }

    .rec-mobile-stack {
        position: absolute;
        inset: 0;
        overflow-y: auto;
        padding: 16px;
        display: flex;
        flex-direction: column;
        gap: 10px;
    }

    .rec-m-banner {
        padding: 10px 14px;
        border-radius: var(--radius);
        font-size: 13px;
        text-align: center;
    }
    .rec-m-banner--error {
        background: rgba(239,68,68,0.12);
        border: 1px solid rgba(239,68,68,0.25);
        color: #fca5a5;
    }
    .rec-m-banner--relaxed {
        background: var(--clr-accent-bg);
        border: 1px solid rgba(201,168,76,0.3);
        color: var(--clr-accent);
    }

    .rec-m-loading {
        padding: 32px 0;
        text-align: center;
        color: var(--clr-text-muted);
        font-size: 14px;
        animation: rec-m-enter 0.3s ease both;
    }

    .rec-m-question {
        background: var(--clr-bg-raised);
        border: 1px solid var(--clr-border);
        border-radius: 10px;
        padding: 16px;
        display: flex;
        flex-direction: column;
        gap: 6px;
        animation: rec-m-enter 0.3s ease both;
    }
    .rec-m-q-type {
        font-size: 10px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        color: var(--clr-accent);
    }
    .rec-m-q-label {
        margin: 0;
        font-size: 16px;
        font-weight: 600;
        color: var(--clr-text);
        line-height: 1.3;
        font-family: var(--font-title);
    }

    .rec-m-options {
        display: flex;
        flex-direction: column;
        gap: 8px;
    }
    .rec-m-option {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 10px;
        padding: 13px 16px;
        background: var(--clr-bg-raised);
        border: 1px solid var(--clr-border);
        border-radius: 8px;
        color: var(--clr-text);
        font-size: 14px;
        cursor: pointer;
        text-align: left;
        transition: border-color var(--transition), background var(--transition);
        animation: rec-m-enter 0.35s cubic-bezier(0.34, 1.4, 0.64, 1) both;
        animation-delay: calc(var(--i) * 65ms + 120ms);
    }
    .rec-m-option:hover {
        border-color: var(--clr-accent);
        background: color-mix(in srgb, var(--clr-accent) 8%, var(--clr-bg-raised));
    }
    .rec-m-opt-label { font-weight: 500; }
    .rec-m-opt-count {
        font-size: 12px;
        color: var(--clr-text-muted);
        flex-shrink: 0;
        font-variant-numeric: tabular-nums;
    }

    .rec-m-result-hd {
        margin: 0;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        color: var(--clr-text-muted);
        animation: rec-m-enter 0.3s ease both;
    }
    .rec-m-results {
        display: flex;
        flex-direction: column;
        gap: 8px;
    }
    .rec-m-game {
        display: flex;
        align-items: center;
        gap: 12px;
        padding: 10px 12px;
        background: var(--clr-bg-raised);
        border: 1px solid var(--clr-border);
        border-radius: 8px;
        text-decoration: none;
        color: var(--clr-text);
        transition: border-color var(--transition), background var(--transition);
        animation: rec-m-enter 0.35s cubic-bezier(0.34, 1.4, 0.64, 1) both;
        animation-delay: calc(var(--i) * 65ms + 80ms);
    }
    .rec-m-game:hover {
        border-color: var(--clr-border-hi);
        background: var(--clr-bg-hover);
    }
    .rec-m-game-img {
        width: 72px;
        height: 34px;
        object-fit: cover;
        border-radius: 4px;
        flex-shrink: 0;
    }
    .rec-m-game-name {
        font-size: 13px;
        font-weight: 500;
        line-height: 1.3;
    }
</style>
